version: "3"
services:
  service_discovery:
    image: discovery
    ports:
      - "8082:8082"
  config_server:
    image: config
    ports:
      - "8081:8081"
  api_gateway:
    image: gateway
    ports:
      - "8080:8080"
  livisi_smarthome_interface:
    image: smarthome
    dns:
      - 192.168.178.1
    ports:
      - "8008:8008"
