version: "3"
services:
  service_discovery:
    image: discovery
    ports:
      - "8082:8082"
    depends_on:
      - config_server
    entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh config_server:8081 -- java -jar app.jar"]
    restart: on-failure
  config_server:
    image: config
    ports:
      - "8081:8081"
    volumes:
      - ./application-config:/config
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/config
    restart: on-failure
  api_gateway:
    image: gateway
    ports:
      - "8080:8080"
    depends_on:
      - config_server
      - service_discovery
    entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh service_discovery:8082 -- java -jar app.jar"]
    restart: on-failure
  livisi_smarthome_interface:
    image: smarthome
    dns:
      - 192.168.178.1
    ports:
      - "8008:8008"
    depends_on:
      - config_server
      - service_discovery
      - api_gateway
    entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh api_gateway:8080 -- java -jar app.jar"]
