name: Deploy Multi-Module Docker Setup to Raspberry Pi

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build smarthome image
        run: |
          docker build -t smarthome:latest ./smartHome
          docker save smarthome:latest -o smarthome.tar

