name: Deploy Multi-Module Docker Setup to Raspberry Pi

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy secrets
        run: |
          tree
          cd smarthome
          touch secrets.properties
          echo ${{ secrets.USERNAME }} >> secrets.properties
          echo ${{ secrets.PASSWORD }} >> secrets.properties
          echo ${{ secrets.AUTH_TOKEN }} >> secrets.properties
          ls -l

      - name: Build images
        run: |
          for module in smartHome Config Discovery Gateway; do
            cd $module
            mvn clean package -DskipTests
            docker build -t $module:latest .
            docker save $module:latest -o ../$module.tar
            cd ..
          done

